/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Chat: typeof import('./src/components/Chat.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    'IBxs:bot': typeof import('~icons/bxs/bot')['default']
    'IIx:closeSmall': typeof import('~icons/ix/close-small')['default']
    'ITabler:abacus': typeof import('~icons/tabler/abacus')['default']
    'ITabler:alertTriangleFilled': typeof import('~icons/tabler/alert-triangle-filled')['default']
    'ITabler:apps': typeof import('~icons/tabler/apps')['default']
    'ITabler:box': typeof import('~icons/tabler/box')['default']
    'ITabler:brandGithub': typeof import('~icons/tabler/brand-github')['default']
    'ITabler:brandHipchat': typeof import('~icons/tabler/brand-hipchat')['default']
    'ITabler:flameFilled': typeof import('~icons/tabler/flame-filled')['default']
    'ITabler:heartFilled': typeof import('~icons/tabler/heart-filled')['default']
    'ITabler:home': typeof import('~icons/tabler/home')['default']
    'ITabler:listSearch': typeof import('~icons/tabler/list-search')['default']
    'ITabler:loader2': typeof import('~icons/tabler/loader2')['default']
    'ITabler:login2': typeof import('~icons/tabler/login2')['default']
    'ITabler:send': typeof import('~icons/tabler/send')['default']
    Modal: typeof import('./src/components/Modal.vue')['default']
    Recommendations: typeof import('./src/components/Recommendations.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
